//action types

export const APP_ACTION_TEST = "APP_ACTION_TEST";
export const APP_ASTRONOMY_DATA_REQUEST = "APP_ASTRONOMY_DATA_REQUEST";
export const SPACE_ASTRONOMY_DATA_REQUEST = "SPACE_ASTRONOMY_DATA_REQUEST";
